services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'imagenes'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'ibA_pX2V5Z-#3:4Tcs'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  flask_app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql

volumes:
  mysql_data:
